default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: BDC1
  username: postgres
  password: richard15
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: BDC1
  username: postgres
  password: richard15
  host: localhost